### ISSUE TITLE
 Compile Error: format-date is not a helper

### ISSUE THREAD

**Issue by MrChriZ** [elwayman02/ember-tumblr#173]
Unless I use formatDates=false
I'm getting an error 
 Compile Error: format-date is not a helper

This is with Ember 2.18 tested in an otherwise empty project.

**Comment by MrChriZ** [comment]
Ah I needed to install ember-intl first.
Can ember-tumblr not install it as pre-req?

If not should formatDates not default to false?

**Comment by elwayman02** [comment]
I agree that it should default to false, I just hadn't gotten around to changing it since it could be fixed manually. I'll put that on my list to address soon!
