### ISSUE TITLE
Ember-Truth-Helpers issue

### ISSUE THREAD

**Issue by MrChriZ** [elwayman02/ember-tumblr#178]
I've just tried to use the new build that you merged from my fork yesterday and it caused my Ember application to fail as I didn't have Ember-Truth-Helpers installed.
As soon as I installed Ember-Truth-Helpers in my application then ember-tumblr started working again.

I had a test fail because it didn't find Ember-Truth-Helpers but I changed the needs line to look for Ember-Truth-Helpers and the test then passed.

I'm assuming there's away for one add-on to install another addon as part of it's install procedure but I'm not quite seeing how that works at the moment.

**Comment by MrChriZ** [comment]
Looks like i just need to move it from devdependencies to dependencies.
I'll create a new pull request.  I'm assuming I should have also bumped the version number up yesterday?

**Comment by elwayman02** [comment]
https://github.com/elwayman02/ember-tumblr/pull/175#discussion_r168284885

:P 

Thanks for catching this, should be an easy fix. I didn't cut a release yet on purpose because I figured you might catch an issue we missed!

**Comment by MrChriZ** [comment]
haha thanks :)
